### ISSUE TITLE
Register 7F?

### ISSUE THREAD

**Issue by jukkapirinen** [rainisto/arduino_i2c_orja#1]
I just started testing this, I can read the data but getting spammed with the data for register 7F all the time.

What is this register 7F (127) and value 0002?
And what are those empty requests?

```
$ cat /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0 |ts  '%Y%m%d-%H:%M:%.S'
20240105-00:52:04.371242 7F=0002
20240105-00:52:04.371347 empty request
20240105-00:52:04.371390 7F=0002
20240105-00:52:04.371422 7F=0002
20240105-00:52:04.371451 7F=0002
20240105-00:52:04.371481 7F=0002
20240105-00:52:04.688652 7F=0002
20240105-00:52:04.688732 7F=0002
20240105-00:52:04.688756 empty request
20240105-00:52:04.688776 empty request
20240105-00:52:05.164298 7F=0002
20240105-00:52:05.164427 7F=0002
20240105-00:52:05.164474 7F=0002
20240105-00:52:05.164512 7F=0002
20240105-00:52:05.164577 7F=0002
20240105-00:52:05.164612 7F=0002
20240105-00:52:05.164646 7F=0002
20240105-00:52:05.243292 7F=0002
20240105-00:52:05.243397 7F=0002
20240105-00:52:05.243430 7F=0002
20240105-00:52:05.243456 7F=0002
20240105-00:52:05.243481 7F=0002
20240105-00:52:05.243509 7F=0002
20240105-00:52:05.243535 7F=0002
20240105-00:52:05.408361 7F=0002
20240105-00:52:05.408489 7F=0002
20240105-00:52:05.408548 7F=0002
20240105-00:52:05.408582 7F=0002
20240105-00:52:05.408612 7F=0002
20240105-00:52:05.408641 empty request
20240105-00:52:05.487329 7F=0002
20240105-00:52:05.487399 7F=0002
20240105-00:52:05.487414 7F=0002
20240105-00:52:05.487426 7F=0002
20240105-00:52:05.487438 7F=0002
20240105-00:52:05.487448 7F=0002
20240105-00:52:05.487459 7F=0002
```

**Comment by rainisto** [comment]
7f is max register, maybe you have accidentally asked that value, and request is not cleared. Maybe off by one bug in code, as usually 74 is the last register that has usable data. What kind of query steps have you made to trigger that? empty request is just debug if wire library doesn't have data. So might also be arduino ide version or library version issue.

If you haven't done any queries, then maybe its initialization off by one, and you can try changing:
for (i=0; i < MAX_REGISTER; i++) {    -->          for (i=0; i <= MAX_REGISTER; i++) {

I just  pushed above bugfix in.

**Comment by jukkapirinen** [comment]
Yes that fixes the initialize, but the real issue was that the readQueue array was too small (0-127= 128) and created infinite loop.

int readQueue[MAX_REGISTER + 1];

https://github.com/jukkapirinen/arduino_i2c_orja/commit/e5ff0c0d8ccd08068f233ab1cf81ee704d306a35

**Comment by jukkapirinen** [comment]
And I did not ask for that value or any value. Just connected to pump and then cat / screen to view the serial output. However now it works with the above changes and also got working with Home Assistant + NodeRED + ThermIQ MQTT Integration

**Comment by rainisto** [comment]
Thanks for the info, I pushed fix to git.
