### ISSUE TITLE
Room sensor emulation

### ISSUE THREAD

**Issue by andresmihkelson** [rainisto/arduino_i2c_orja#2]
Thank You for all the good work on reverse engineering the I2C communication on the EXT port.

You have mentioned in couple of forums that You also got the indoor room sensor interface (pins 303/304) working. Can You share any details on how it is implemented?

**Comment by rainisto** [comment]
It will be 2 part blog post, second part will still take some more time before its ready for publishing. But I guess the 1 / 2 part is ready (so I published it now) which will tell the logic analyzing and solving out that it was Manchester code variant and how the protocol works in paper. Its in Finnish so you'll need to use google translator. https://omakotikotitalomme.blogspot.com/2024/01/danfoss-sisalampotilasensorin.html

**Comment by andresmihkelson** [comment]
Thanks!
